kabisa/kudos-frontend

- src/modules/statistics/StatisticsPage.js
- src/modules/statistics/components/DonutChart.js
- src/modules/statistics/components/index.js
- src/styles/elements/base.scss
- src/styles/elements/donut.scss
> Donut visualization for statistics page

- src/modules/feed/FeedPage.js
- src/modules/feed/queries.js
Load more button at the bottom of the feed to load more posts.
> Load more button for feed page

- src/modules/login/ForgotPasswordPage.js
- src/modules/login/LoginPage.js
- src/modules/login/RegisterPage.js
- src/support/graphqlError.js
- src/support/index.js
Now using messages that the backend returns for appropriate responses.
> Improved error messages

- src/modules/feed/components/Transaction/CommentButton/CommentButton.js
- src/modules/feed/components/Transaction/Transaction.js
ESLint disable is to prevent ESLint from throwing an error on the first parameter.
> Temporarily disabled comments button

- src/modules/feed/AddTransactionPage.js
- src/modules/feed/AddTransactionPage.scss
- src/modules/feed/components/GuidelineInput/GuidelineInput.js
- src/modules/feed/components/index.js
> Guidelines

- src/modules/choose-team/ChooseTeamPage.js
What do you think, is 2 seconds the right amount for the polling interval?
> Poll available teams

- package.json
- schema.json
- src/components/navigation/Desktop.js
- src/config/settings.default.js
- src/modules/choose-team/CreateTeamPage.js
- src/modules/choose-team/components/Invite.js
- src/modules/choose-team/components/InviteList.js
- src/modules/choose-team/components/TeamList.js
- src/modules/feed/FeedPage.js
- src/modules/feed/components/CreatePost.js
- src/modules/feed/components/GoalProgress/GoalProgress.scss
- src/modules/feed/components/LeftRail.js
- src/modules/feed/components/Transaction/Header.js
- src/modules/feed/components/Transaction/LikeButton.js
- src/modules/feed/queries.js
- src/modules/login/FinishForgotPasswordPage.js
- src/modules/login/LoginPage.js
- src/modules/login/RegisterPage.js
- src/modules/settings/InvitePage.js
- src/modules/statistics/Statistics.js
- src/modules/user/ResetPasswordPage.js
- src/modules/user/UserPage.js
Because of the class-styled api there are some things different in how the data is queried. See https://github.com/kabisa/kudo-o-matic/pull/487 for all changes.
> Refactored several queries and mutations

- CHANGELOG.md
- src/modules/manage-team/ManageTeamPage.tsx
- src/modules/manage-team/sections/kudometer/KudometerQuerries.ts
- src/modules/manage-team/sections/kudometer/KudometerRow.spec.tsx
- src/modules/manage-team/sections/kudometer/KudometerRow.tsx
- src/modules/manage-team/sections/kudometer/KudometerSection.spec.tsx
- src/modules/manage-team/sections/kudometer/KudometerSection.tsx
- Allow kudometer names to be changed
- Allow the active kudometer to be set
> Allow editing of kudometers

- src/modules/user/SlackSection.tsx
- src/modules/user/UserPage.spec.tsx
- src/modules/user/UserPage.tsx
- Users can disconnect their Kudo-O-Matic account from Slack
See the corresponding [backend PR](https://github.com/kabisa/kudo-o-matic/pull/27) as well.
> Add disconnect from slack button

- src/modules/feed/components/CreatePost.tsx
The post creation was working but it would always show an error because it was trying to call a method on an undefined component when resetting the state.
> Correctly reference inputs in create post component

- src/ui/Button/Button.spec.tsx
- src/ui/Button/Button.stories.tsx
- src/ui/Button/index.tsx
- src/ui/InputField/InputField.stories.tsx
- src/ui/InputField/index.tsx
- src/ui/InputField/styles.module.css
> Improve button story and add input component

- .eslintignore
- package.json
> Remove dist folder

- src/components/navigation/Desktop.module.css
- src/modules/statistics/GoalSection.module.scss
> Temporary fix for icons.

- src/modules/manage-team/sections/guideline/EditGuideline.tsx
> Prevent default form behaviour on submit

- src/modules/manage-team/sections/member/MemberRow.tsx
> Fix remove member.

- src/ui/Button/Button.spec.tsx
- src/ui/Button/Button.stories.tsx
- src/ui/Button/index.tsx
- src/ui/Button/styles.module.css
> Feature/button UI expansion

- .gitignore
- src/modules/feed/components/GuidelineInput/GuidelineInput.tsx
The kudos amount input is losing focus because a rerender is executed on change. I enabled autofocus on mount to resolve this.
> Fix kudos amount input losing focus

- src/modules/manage-team/sections/guideline/GuidelinesSection.tsx
- src/modules/manage-team/sections/kudometer/KudometerQueries.ts
- src/modules/manage-team/sections/kudometer/KudometerSection.tsx
> Fix management lists not updating on crud actions

- src/modules/choose-team/CreateTeamPage.tsx
- src/modules/feed/components/CreatePost/CreatePost.tsx
- src/modules/login/FinishForgotPasswordPage.tsx
- src/modules/login/ForgotPasswordPage.tsx
- src/modules/login/LoginPage.tsx
- src/modules/login/RegisterPage.tsx
- src/modules/manage-team/sections/guideline/EditGuideline.tsx
- src/modules/manage-team/sections/invite/CreateInvite.tsx
- src/modules/manage-team/sections/kudometer/goals/EditGoal.tsx
- src/ui/MessageBox/index.module.css
- src/ui/MessageBox/index.spec.tsx
- src/ui/MessageBox/index.stories.tsx
- src/ui/MessageBox/index.tsx
> Add MessageBox component

- src/components/Toast/Toast.module.css
- src/components/Toast/Toast.tsx
> Style toast loader

- src/ui/Progress/Progress.spec.tsx
- src/ui/Progress/Progress.stories.tsx
- src/ui/Progress/index.tsx
- src/ui/Progress/styles.module.css
> Refactor kudo component.

- .storybook/preview.ts
- src/ui/Toast/Toast.module.css
- src/ui/Toast/Toast.stories.tsx
- src/ui/Toast/index.tsx
> Add Toast Component

- src/ui/Button/Button.spec.tsx
- src/ui/Button/Button.stories.tsx
- src/ui/Button/LikeButton.spec.tsx
- src/ui/Button/LikeButton.tsx
- src/ui/Button/index.tsx
- src/ui/Button/styles.module.css
- src/ui/Button/types.ts
> Add like button component.

- src/modules/feed/components/GuidelineInput/GuidelineInput.tsx
> Fix tabbing problem.

- src/modules/feed/components/GuidelineInput/GuidelineInput.tsx
> Fix autoFocus issue when typing in message box

- src/modules/choose-team/ChooseTeamPage.tsx
- src/modules/choose-team/components/ChoiceButton.tsx
- src/modules/choose-team/components/TeamRow.tsx
- src/ui/Button/index.tsx
Replaces all button occurrences with the new UI Button in ChooseTeamPage
--
> Replace button in ChooseTeamPage with new Button

- src/modules/user/UserPage.module.css
- src/modules/user/UserPage.tsx
- src/modules/user/components/SlackSection.module.scss
- src/modules/user/components/SlackSection.tsx
- src/ui/Button/index.tsx
- src/ui/Button/styles.module.css
Refactors the user page to use the new UI button. 
> Replace Button with new Button in User Page

- src/modules/manage-team/ManageTeamPage.module.css
- src/modules/manage-team/ManageTeamPage.module.scss
- src/modules/manage-team/ManageTeamPage.spec.tsx
- src/modules/manage-team/ManageTeamPage.tsx
- src/ui/Card/index.tsx
> Refactor - Kudo card in manage team page

- TECH_DEBT.md
Adds TECH_DEBT document to keep track of technical debt.
> Added TECH_DEBT.md document

- .github/workflows/nodejs.yml
- src/modules/feed/components/Transaction/Header.spec.tsx
- src/modules/feed/components/Transaction/Transaction.spec.tsx
> Remove unused imports
